version: '3'

services:
  overview:
    build: .

    depends_on:
      - 'database'
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=development
      - PROD_API_URL=localhost:80
      - PROD_DB_HOST=database
      - DEV_DB_HOST=database

  database:
    image: mongo:latest