version: '3'

services:
  overview:
    build: .
    volumes:
      - .:/src/app
      - /app/node_modules

    depends_on:
      - 'database'
    ports:
      - '3000:3000'

  database:
    image: mongo:latest